//KeypadAction
export const ADD_TOKEN = 'ADD_TOKEN'
export const UPDATE_TOKENLIST = 'UPDATE_TOKENLIST'
export const UPDATE_DISPLAY_VALUE = 'UPDATE_DISPLAY_VALUE'
export const UPDATE_CALCHISTORY = 'UPDATE_CALCHISTORY '

//Theme Action
export const CHANGE_THEME = 'CHANGE_THEME'
