//KeypadAction
export const ADDITION = 'ADDITION'
export const SUBSTRACTION = 'SUBSTRACTION'
export const MULTIPLY = 'MULTIPLY'
export const DEVIDE = 'DEVIDE'
export const SET_0 = 'SET_0'
export const SET_1 = 'SET_1'
export const SET_2 = 'SET_2'
export const SET_3 = 'SET_3'
export const SET_4 = 'SET_4'
export const SET_5 = 'SET_5'
export const SET_6 = 'SET_6'
export const SET_7 = 'SET_7'
export const SET_8 = 'SET_8'
export const SET_9 = 'SET_9'
export const EQUAL = 'EQUAL'
export const RESET_LAST_NUMBER = 'RESET_LAST_NUMBER'
export const TOTAL_RESET = 'TOTAL_RESET'
export const SET_FLOAT_POINT = 'SET_FLOAT_POINT'
export const SET_RIGHT_BRACKET = 'SET_RIGHT_BRACKET'
export const SET_LEFT_BRACKET = 'SET_LEFT_BRACKET'

//Theme Action
export const CHANGE_THEME = 'CHANGE_THEME'
