export const OPERATORS = [
  {
    id: 'op-power',
    numOperands: 2,
    symbol: ' ^ ',
    calc: (a, b) => Math.pow(a, b),
  },
  {
    id: 'op-negate',
    numOperands: 1,
    symbol: ' -',
    calc: (a) => -a,
  },
  {
    id: 'op-square-root',
    numOperands: 1,
    symbol: ' √',
    calc: (a) => Math.sqrt(a),
  },
  {
    id: 'op-log',
    numOperands: 1,
    symbol: ' log ',
    calc: (a) => Math.log10(a),
  },
  {
    id: 'op-natural-log',
    numOperands: 1,
    symbol: ' ln ',
    calc: (a) => Math.log(a),
  },
  {
    id: 'op-sin',
    numOperands: 1,
    symbol: ' sin ',
    calc: (a) => Math.sin(a),
  },
  {
    id: 'op-cos',
    numOperands: 1,
    symbol: ' cos ',
    calc: (a) => Math.cos(a),
  },
  {
    id: 'op-tan',
    numOperands: 1,
    symbol: ' tan ',
    calc: (a) => Math.tan(a),
  },
  {
    id: 'op-inverse-sin',
    numOperands: 1,
    symbol: ' sin-1 ',
    calc: (a) => Math.asin(a),
  },
  {
    id: 'op-inverse-cos',
    numOperands: 1,
    symbol: ' cos-1 ',
    calc: (a) => Math.acos(a),
  },
  {
    id: 'op-inverse-tan',
    numOperands: 1,
    symbol: ' tan-1 ',
    calc: (a) => Math.atan(a),
  },
  {
    id: 'op-e',
    numOperands: 1,
    symbol: ' e ^ ',
    calc: (a) => Math.exp(a),
  },
  {
    id: 'op-nth-root',
    numOperands: 2,
    symbol: '*√',
    calc: (a, b) => Math.pow(b, 1 / a),
  },
  {
    id: 'op-multiply',
    numOperands: 2,
    symbol: ' x ',
    calc: (a, b) => a * b,
  },
  {
    id: 'op-divide',
    numOperands: 2,
    symbol: ' ÷ ',
    calc: (a, b) => a / b,
  },
  {
    id: 'op-add',
    numOperands: 2,
    symbol: ' + ',
    calc: (a, b) => a + b,
  },
  {
    id: 'op-subtract',
    numOperands: 2,
    symbol: ' - ',
    calc: (a, b) => a - b,
  },
]
