export const FETCH_WEATHER = 'FETCH_WEATHER'
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS'
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR'
export const ADD_WEATHER = 'ADD_WEATHER'

export const FETCH_LOCATION = 'FETCH_LOCATION'
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS'
export const FETCH_LOCATION_ERROR = 'FETCH_LOCATION_ERROR'
